src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastLogin = null;

    #[ORM\OneToMany(mappedBy: 'likedBy', targetEntity: Like::class)]
    private Collection $likes;

    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Article::class)]
    private Collection $articles;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePicture = null;

    #[ORM\Column(nullable: true)]
    private ?bool $admin = null;

    public function __toString(): string
    {
        return substr($this->pseudo, 0, 20) . '...';
    }

    public function __construct()
    {
        $this->likes = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setLikedBy($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getLikedBy() === $this) {
                $like->setLikedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setCreatedBy($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCreatedBy() === $this) {
                $comment->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setCreatedBy($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCreatedBy() === $this) {
                $article->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function isAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(?bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Like;
use App\Entity\User;
use App\Form\CreateArticleType;
use App\Form\ProfilePictureType;
use App\Repository\ArticleRepository;
use App\Repository\LikeRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(ArticleRepository $articleRepository, Request $request): Response
    {
        date_default_timezone_set('Europe/Paris');
        $article = new Article();
        $form = $this->createForm(CreateArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('image')->getData() != null) {
                $file = $form->get('image')->getData();
                $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                $file->move($this->getParameter('article_images'), $fileName);
                $article->setImage($fileName);
            }
            $article->setCreatedAt(new \DateTimeImmutable());
            $article->setCreatedBy($this->getUser());

            $articleRepository->save($article, true);
        }

        return $this->render('main/index.html.twig', [
            'articles' => $articleRepository->findAll(),
            'form' => $form,
        ]);
    }

    #[Route('/search', name: 'app_search')]
    public function search(Request $request, ArticleRepository $articleRepository)
    {
        $query = $request->query->get('search');
        $articles = $articleRepository->findBySearch($query);
        // Perform your search logic here...

        return $this->render('main/search.html.twig', [
            'query' => $query,
            'articles' => $articles,
        ]);
    }
}

templates/main/article-details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}

    {{ include('_includes/navigation.html.twig') }}
    {% set isMore3CommentToDisplay = true %}
    <div class="max-w-xl mx-auto mt-28">
        {{ include('_includes/article.html.twig') }}
        {% if app.user %}
            {{ include('_includes/create-comment.html.twig') }}
        {% endif %}
    </div>
    <script src="{{ asset('js/like.js') }}"></script>
    <script src="{{ asset('js/likeComment.js') }}"></script>
{% endblock %}

templates/main/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}

    {{ include('_includes/navigation.html.twig') }}
    <div class="max-w-xl mx-auto mt-28">
        <div class="border border-gray-200 rounded-lg p-4 my-4">
            <div class="flex items-center">
                <img class="w-12 h-12 rounded-full mr-4" src="https://picsum.photos/id/1005/200/200"
                     alt="John Doe's avatar">
                <div>
                    <h2 class="font-bold">{{ article.createdBy.pseudo }}</h2>
                    <p class="text-gray-500">Posté le {{ article.createdAt|date("d/m/Y à H:i") }}</p>
                </div>
            </div>
            <p class="mt-4">{{ article.content }}</p>
            <div class="flex items-center mt-4">
                <button class="text-gray-500 hover:text-blue-500">
                    <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round">
                        <path d="M20.84 4.22a5.5 5.5 0 0 0-7.78 0L12 5.45l-1.06-1.23a5.5 5.5 0 0 0-7.78 0 5.5 5.5 0 0 0 0 7.78L12 21.71l8.84-8.84a5.5 5.5 0 0 0 0-7.78z"></path>
                    </svg>
                    <span class="ml-2">{{ article.likes|length }}</span>
                </button>
                <button class="ml-4 text-gray-500 hover:text-blue-500">{{ article.comments|length }} Comments</button>
            </div>
            <div class="mt-4">
                {% for comment in article.comments %}
                    <div class="border border-gray-200 rounded-lg p-4 my-4">
                        <div class="flex items-center">
                            <img class="w-8 h-8 rounded-full mr-4" src="https://picsum.photos/id/1006/200/200"
                                 alt="Jane Doe's avatar">
                            <div>
                                <h3 class="font-bold">Jane Doe</h3>
                                <p class="text-gray-500">April 28, 2023 at 2:35 PM</p>
                            </div>
                        </div>
                        <p class="mt-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod ante vitae
                            elit
                            posuere, non pellentesque nisl hendrerit.</p>
                    </div>
                {% endfor %}

            </div>
        </div>
        {% if app.user %}
            <div class="border border-gray-200 rounded-lg p-4 my-4">
                <div class="flex items-center">
                    <img class="w-12 h-12 rounded-full mr-4" src="https://picsum.photos/id/1008/200/200"
                         alt="Sarah Johnson's avatar">
                    <div>
                        <h2 class="font-bold">{{ app.user.pseudo }}</h2>
                    </div>
                </div>
                <form class="mt-4">
                    <div class="mb-4">
                        <label class="block text-gray-700 font-bold mb-2" for="comment_content">Comment:</label>
                        <textarea
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="comment_content" name="comment_content" placeholder="Enter your comment"></textarea>
                    </div>
                    <div class="flex items-center">
                        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                                type="submit">Post Comment
                        </button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
    {{ include('_includes/navigation.html.twig') }}
    {% set isMore3CommentToDisplay = false %}
    <div class="max-w-xl mx-auto mt-28">
        {% if app.user and app.user.verified %}
            {{ include('article/create-article.html.twig') }}
        {% elseif not app.user %}
            <div class="bg-blue-100 border border-blue-400 text-gray-700 px-4 py-3 rounded mb-4" role="alert">
                You have to be logged in to post a tweet.
            </div>
        {% else %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4" role="alert">
                Verify your email address to post a tweet.
            </div>
        {% endif %}
        {% for message in app.flashes('success') %}

            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <div>
            <h2 class="text-xl font-bold mb-4 dark:text-gray-200">Recent Tweets</h2>
            <ul>
                {% if articles|length == 0 %}
                    <li class="border border-gray-200 rounded-lg p-4 my-4">
                        <p class="text-gray-500">No tweets found.</p>
                    </li>
                {% endif %}
                {% for article in articles|reverse %}
                    {{ include('article/article.html.twig') }}
                {% endfor %}
                {{ include('article/article-image-modal.html.twig') }}
            </ul>
        </div>
    </div>
    <script src="{{ asset('js/like.js') }}"></script>
    <script src="{{ asset('js/likeComment.js') }}"></script>
{% endblock %}

templates/main/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
    {{ include('_includes/navigation.html.twig') }}
    {% set isMore3CommentToDisplay = false %}
    <div class="max-w-xl mx-auto mt-28">
        {% for message in app.flashes('success') %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <div>
            <h2 class="text-xl font-bold mb-4 dark:text-gray-200">Search results for "{{ query }}"</h2>
            <ul>
                {% if articles|length == 0 %}
                    <li class="border border-gray-200 rounded-lg p-4 my-4">
                        <p class="text-gray-500">No tweets found with "{{ query }}".</p>
                    </li>
                {% else %}
                    <p class="text-gray-500 dark:text-gray-400">{{ articles|length }} Articles found</p>
                {% endif %}
                {% for article in articles|reverse %}
                    {{ include('article/article.html.twig') }}
                {% endfor %}
            </ul>
        </div>
    </div>

    <script src="{{ asset('js/like.js') }}"></script>
    <script src="{{ asset('js/likeComment.js') }}"></script>
{% endblock %}